### ISSUE TITLE
Uncaught Error: Handler must be a function

### ISSUE THREAD

**Issue by rsakib15** [leny/atom-w3c-validation#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package, v0.2.0
### Stack Trace

Uncaught Error: Handler must be a function

```
At C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:37

Error: Handler must be a function
    at Emitter.module.exports.Emitter.on (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:37:15)
    at TextBuffer.module.exports.TextBuffer.onDidChange (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:197:27)
    at C:\Users\SAKIB\.atom\packages\w3c-validation\lib\main.coffee:75:40
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\src\workspace.js:276:9)
    at C:\Users\SAKIB\.atom\packages\w3c-validation\lib\main.coffee:72:31
    at C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\src\config.js:557:16
    at C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\src\config.js:574:20
    at Emitter.module.exports.Emitter.emit (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\src\config.js:736:29)
    at Config.module.exports.Config.setRawValue (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\src\config.js:551:19)
    at Config.module.exports.Config.set (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\src\config.js:233:14)
    at SettingsPanel.module.exports.SettingsPanel.set (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:190:28)
    at setNewValue (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:132:28)
    at HTMLInputElement.<anonymous> (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:138:22)
    at HTMLInputElement.jQuery.event.dispatch (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (C:\Users\SAKIB\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```
### Commands

```
     -2:16.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:16.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:14 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:14 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:13.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:12.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:12.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:10.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:10.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:09.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:54.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:53.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:12 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:12 editor:newline (atom-text-editor.editor.is-focused)
     -1:08.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "html-include-resource"
    ]
  },
  "w3c-validation": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
color-picker, v2.0.7
csslint, v1.1.3
emmet, v2.3.10
file-icons, v1.5.8
javascript-snippets, v1.0.0
jslint, v1.4.0
punchclock, v0.5.0
run-in-browser, v0.1.3
time-status, v1.1.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by IIYAMA12** [comment]
I have same problem, @rsakib15 were you able to fix it?

**Comment by rsakib15** [comment]
No i can't fix it.

**Comment by leny** [comment]
Hi, sorry for the _long_ time on this one, was very busy with my work.

I've just released a new version (`0.3.0`) of the package, using new modules for validation.

Hope it will fix this issue.

**Comment by sandro-git** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package, v0.4.0


### Stack Trace

Uncaught Error: Handler must be a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:80

Error: Handler must be a function
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:80:15)
    at TextBuffer.module.exports.TextBuffer.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:267:27)
    at /Users/sandro/.atom/packages/w3c-validation/lib/main.js:85:37
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)
    at /Users/sandro/.atom/packages/w3c-validation/lib/main.js:83:24
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:618:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:200:28)
    at setNewValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:136:28)
    at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:142:22)
    at HTMLInputElement.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:19.3.0 autocomplete-plus:cancel (input.hidden-input)
     -2:18 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -2:15.9.0 core:move-down (input.hidden-input)
     -2:14.6.0 core:save (input.hidden-input)
     -1:47.1.0 command-palette:toggle (input.hidden-input)
     -1:41.1.0 core:close (input.hidden-input)
     -1:34.2.0 core:confirm (input.hidden-input)
  4x -1:22.3.0 core:close (div.panels-item)
  2x -1:13.9.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:56.1.0 command-palette:toggle (input.hidden-input)
  5x -0:49.2.0 core:backspace (input.hidden-input)
     -0:47.4.0 application:open (input.hidden-input)
     -0:46.4.0 editor:consolidate-selections (input.hidden-input)
     -0:46.4.0 core:cancel (input.hidden-input)
  2x -0:44.1.0 application:open (input.hidden-input)
     -0:31 core:close (input.hidden-input)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "reopenProjectMenuCount": 5,
    "telemetryConsent": "limited",
    "useCustomTitleBar": true
  },
  "w3c-validation": {
    "hideOnNoErrors": true,
    "useFoldModeAsDefault": true,
    "validateOnChange": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.5 (active)
emmet, v2.4.3 (active)
jquery-snippets, v11.0.0 (active)
linter, v1.11.21 (active)
linter-jshint, v3.0.2 (active)
pigments, v0.39.0 (active)
w3c-validation, v0.4.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by leny** [comment]
Hi, thanks for the reporting. 

I'm not an active user of Atom anymore (switched to vim a few months ago), but, for now, I'm mostly too busy with professional work and deadlines to be able to fix this package before a few months.

If anyone of you want to become a collaborator and do the work, I will be happy to include this person(s) on the collaborators list of the package.

Thanks :)

**Comment by Isma3ailos** [comment]
did any body figured it out
