### ISSUE TITLE
Bug: when activating "Validate on Change" option

### ISSUE THREAD

**Issue by anasabufarraj** [leny/atom-w3c-validation#21]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.3
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package, v0.4.0
### Stack Trace

Uncaught Error: Handler must be a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:80

Error: Handler must be a function
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:80:15)
    at TextBuffer.module.exports.TextBuffer.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:234:27)
    at /Users/anasabufarraj/.atom/packages/w3c-validation/lib/main.js:85:37
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:288:9)
    at /Users/anasabufarraj/.atom/packages/w3c-validation/lib/main.js:83:24
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:606:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:623:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:808:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:600:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:196:28)
    at setNewValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:138:28)
    at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:144:22)
    at HTMLInputElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
  2x -9:26.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:48.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -7:48.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -7:48 editor:indent (atom-text-editor.editor.is-focused)
  2x -7:46.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:59.7.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -6:58.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:14.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:44.6.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/anasabufarraj",
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  },
  "w3c-validation": {}
}
```
### Installed Packages

``` coffee
# User
w3c-validation, v0.4.0

# Dev
No dev packages
```

**Comment by tony19** [comment]
I'm also seeing this issue with v0.4.0. This seems to be a duplicate of #10.
