### ISSUE TITLE
Failed to load the w3c-validation package

### ISSUE THREAD

**Issue by michele-prandina** [leny/atom-w3c-validation#25]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.3
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package, v0.4.0
### Stack Trace

Failed to load the w3c-validation package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/prodesfin3/.atom/packages/w3c-validation/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:8:9)
    at Object.<anonymous> (/Users/prodesfin3/.atom/packages/w3c-validation/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:627:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/prodesfin3/.atom/packages/w3c-validation/node_modules/atom-message-panel/lib/MessagePanelView.js:4:7)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/prodesfin3/.atom/packages/w3c-validation/node_modules/atom-message-panel/lib/index.js:2:21)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/prodesfin3/.atom/packages/w3c-validation/lib/validator.js:7:25)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-live-server",
      "tool-bar-main",
      "jshint"
    ],
    "packagesWithKeymapsDisabled": [
      "navigate"
    ],
    "themes": [
      "genesis-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
api-docs, v0.0.4
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.8
genesis-ui, v0.5.0
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
language-babel, v2.19.3
language-javascript-jsx, v0.3.7
language-javascript-semantic, v0.2.1
linter, v1.11.4
linter-htmlhint, v1.1.4
linter-jshint, v2.1.0
minimap, v4.23.2
minimap-highlight-selected, v4.4.0
pigments, v0.26.0
react, v0.15.0
react-es6-snippets, v0.3.0
rest-client, v1.1.0
sync-settings, v0.7.2
synced-sidebar, v0.4.3
terminal-plus, v0.14.5
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1
w3c-validation, v0.4.0

# Dev
No dev packages
```

**Comment by design1online** [comment]
Did you try going into the package folder and running `npm install && apm link`? I didn't have this exact error but I had something similar and that fixed it.
