### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by masoomulhaqs** [leny/atom-w3c-validation#31]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/masoom/.atom/packages/w3c-validation/node_modules/atom-message-panel/lib/LineMessageView.js:52

TypeError: Cannot read property 'getPath' of undefined
    at LineMessageView.goToLine (/Users/masoom/.atom/packages/w3c-validation/node_modules/atom-message-panel/lib/LineMessageView.js:52:53)
    at HTMLPreElement.<anonymous> (/Users/masoom/.atom/packages/w3c-validation/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLPreElement.dispatch (/Users/masoom/.atom/packages/w3c-validation/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLPreElement.elemData.handle (/Users/masoom/.atom/packages/w3c-validation/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:17.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:17.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:17.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:09.5.0 core:paste (atom-text-editor.editor.is-focused)
     -4:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:05.3.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -3:05.3.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -3:04.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:52.5.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -2:52.5.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
 14x -2:52.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:50.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:49.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:46.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:46.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
angular-bootstrap, v1.0.1 (inactive)
atom-beautify, v0.29.14 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-typescript, v10.1.13 (active)
autoclose-html, v0.23.0 (active)
autoprefixer, v3.6.0 (active)
bootstrap-sass-snippets, v0.1.0 (active)
emmet, v2.4.3 (active)
linter, v1.11.18 (active)
markdown-preview-plus, v2.4.0 (active)
markdown-writer, v2.6.2 (active)
project-manager, v3.3.3 (active)
w3c-validation, v0.4.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by leny** [comment]
Hi, thanks for the reporting. 

I'm not an active user of Atom anymore (switched to vim a few months ago), but, for now, I'm mostly too busy with professional work and deadlines to be able to fix this package before a few months.

If anyone of you want to become a collaborator and do the work, I will be happy to include this person(s) on the collaborators list of the package.

Thanks :)
