### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by bigdaze** [leny/atom-w3c-validation#33]
[Enter steps to reproduce:]

1. control s

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package 0.4.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At events.js:160

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /packages/w3c-validation/node_modules/superagent/lib/node/parsers/json.js:9:31)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:54.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:54.3.0 editor:newline (input.hidden-input)
     -0:43 core:backspace (input.hidden-input)
     -0:17.8.0 snippets:previous-tab-stop (input.hidden-input)
     -0:17.8.0 editor:outdent-selected-rows (input.hidden-input)
     -0:17.1.0 snippets:previous-tab-stop (input.hidden-input)
     -0:17.1.0 editor:outdent-selected-rows (input.hidden-input)
     -0:13.1.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:13 editor:newline (input.hidden-input)
     -0:10.6.0 core:move-up (input.hidden-input)
     -0:09.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:07.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-monokai 0.10.9 
emmet 2.4.3 
git-plus 7.3.3 
minimap 4.26.8 
monokai 0.22.0 
seti-icons 1.4.3 
w3c-validation 0.4.0 
```

**Comment by leny** [comment]
Hi, thanks for the reporting. 

I'm not an active user of Atom anymore (switched to vim a few months ago), but, for now, I'm mostly too busy with professional work and deadlines to be able to fix this package before a few months.

If anyone of you want to become a collaborator and do the work, I will be happy to include this person(s) on the collaborators list of the package.

Thanks :)
