### ISSUE TITLE
Failed to activate the w3c-validation package

### ISSUE THREAD

**Issue by MCorneliu** [leny/atom-w3c-validation#38]
Handler must be a function
Hide Stack Trace
Error: Handler must be a function
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:80:21)
    at TextBuffer.module.exports.TextBuffer.onDidChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:366:33)
    at /Users/cornelium/.atom/packages/w3c-validation/lib/main.js:85:37
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:728:15)
    at /Users/cornelium/.atom/packages/w3c-validation/lib/main.js:83:24
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:674:13)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:155:27)
    at Object.fActivate [as activate] (/Users/cornelium/.atom/packages/w3c-validation/lib/main.js:82:17)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:30)
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:407:18)
    at Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:31)

**Comment by leny** [comment]
Hi, thanks for the issue ; I don't use Atom since a year and half (switched to _vim_), and I don't have any time to look at this for the moment.
I'll be happy to accept any Pull Request and/or assign a new collaborator to maintain this package.

**Comment by MCorneliu** [comment]
hi,thanks for your answer, I'll look for something else, because I'm new to programming
