### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by guribundis** [leny/atom-w3c-validation#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Linux Mint
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package, v0.2.0
### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (NaN, 0)
  at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:956:13)
  at MarkerStore.module.exports.MarkerStore.setMarkerRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-store.js:305:50)
  at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:324:20)
  at Marker.module.exports.Marker.setHeadPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/usr/share/atom/resources/app.asar/src/marker.js:175:32)
  at /usr/share/atom/resources/app.asar/src/cursor.js:136:31
  at Cursor.module.exports.Cursor.changePosition (/usr/share/atom/resources/app.asar/src/cursor.js:683:7)
  at Cursor.module.exports.Cursor.setBufferPosition (/usr/share/atom/resources/app.asar/src/cursor.js:134:19)
  at [object Object].LineMessageView.goToLine (/home/garbbos/.atom/packages/w3c-validation/node_modules/atom-message-panel/lib/LineMessageView.js:60:53)
  at HTMLDivElement.<anonymous> (/home/garbbos/.atom/packages/w3c-validation/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLDivElement.jQuery.event.dispatch (/home/garbbos/.atom/packages/w3c-validation/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/home/garbbos/.atom/packages/w3c-validation/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:46)

```
### Commands

```
  5x -9:33.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:29.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 12x -9:24.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:20.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:53 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:42.7.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -1:41.4.0 core:delete (atom-text-editor.editor.is-focused)
     -0:38.3.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:18.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ],
    "autoHideMenuBar": true,
    "projectHome": "/home/garbbos/src/html/proyectos",
    "disabledPackages": [
      "css-color-highlight",
      "css-color-highlight",
      "css-color-highlight",
      "outdoor-theme",
      "outdoor-theme",
      "outdoor-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.5
atom-html-preview, v0.1.8
atom-python-debugger, v0.3.3
autoclose-html, v0.18.0
autocomplete-python, v0.4.2
javascript-snippets, v1.0.0
jsformat, v0.9.0
jshint, v1.3.7
language-javascript-semantic, v0.2.1
unity-ui, v2.0.11
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by leny** [comment]
Hi, sorry for the _long_ time on this one, was very busy with my work.

I've just released a new version (`0.3.0`) of the package, using new modules for validation.

Hope it will fix this issue.
